version: 2
updates:
  - package-ecosystem: "pip"
    schedule:
      interval: "monthly"
      timezone: "Europe/Amsterdam"
    labels:
      - "dependencies"
    commit-message:
      prefix: "OPT:"
    open-pull-requests-limit: 0
