# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "Cachetory"
site_description: "Caching library with support for multiple cache backends"

nav:
  - index.md
  - getting-started.md
  - caches.md
  - decorators.md
  - shortcuts.md
  - Backends:
      - backends/dummy.md
      - backends/memory.md
      - backends/redis.md
      - backends/django.md
  - Serializers:
      - serializers/noop.md
      - serializers/pickle.md
      - serializers/json.md
      - serializers/msgpack.md
      - serializers/chained.md
      - Compressors:
          - serializers/compressors/index.md
          - serializers/compressors/zlib.md
          - serializers/compressors/zstandard.md

theme:
  icon:
    repo: "fontawesome/brands/github"
    logo: "material/food-takeout-box"
  name: material
  features:
    - content.action.view
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: System theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
      primary: green
      accent: green
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: green
      accent: green

plugins:
  - autorefs
  - git-revision-date-localized:
      enable_creation_date: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            line_length: 80
            members_order: "source"
            merge_init_into_class: false
            separate_signature: true
            show_bases: false
            show_root_heading: true
            show_root_toc_entry: false
            show_signature_annotations: true
            show_source: true
  - search:
      lang: en
  - social
  - git-committers:
      repository: kpn/cachetory
      branch: main

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

repo_url: https://github.com/kpn/cachetory
edit_uri: edit/main/docs/

extra:
  social:
    - icon: material/github
      link: https://github.com/kpn
      name: KPN on GitHub
    - icon: material/office-building
      link: https://jobs.kpn.com/
      name: Working at KPN

copyright: Copyright &copy; 2023 Koninklijke KPN N.V.

site_url: "https://kpn.github.io/cachetory"

watch:
  - "cachetory"
